### ISSUE TITLE
ssd1322 and othe chip support

### ISSUE THREAD

**Issue by p1234321** [noopkat/oled-js#108]
hello, great work!!!
would it be possible to use different displays than the ssd1306?
i'm asking because i'm currently trying to connect an ssd1322 to my raspberry via nodejs.
i found a great library, but its just for c... (https://github.com/olikraus/u8glib)
it would be amazing to port this to nodejs to your oled-js module.
best regards

paul

**Comment by noopkat** [comment]
Hi! Thanks for opening this issue, that's a great question about chipset support!

Initially I was aiming to support more chipsets such as the SD1322, however I didn't receive enough interest at the time to pursue this. Happy to receive a pull request, otherwise it might happen in future if I get the time to sit down and code it out. 😁
