### ISSUE TITLE
SPI resources

### ISSUE THREAD

**Issue by pjebs** [noopkat/oled-js#148]
Hi @noopkat,

I came across your oled-js project.
I'm trying to draw on a e-ink display module which requires SPI.

I was wondering if you can point me to the best resources you managed to find on how to use SPI as efficiently as possible. For your project, you mentioned it is slow when using SPI. (I'm trying to make a second e-ink display HDMI monitor).

It's also nice to see a fellow Melburnian make it to the big leagues in the US. Keep up the good work! I wouldn't be surprised if I've actually met you at a meetup or two either.

Regards,

PJ

**Comment by noopkat** [comment]
Hi @pjebs!

Thanks for opening this issue. Your project sounds super cool as the off the shelf versions are _so_ expensive and I also want an e-ink monitor :smile:

I couldn't tell from your question if you were looking to use this library with the display, and sorry if you knew this but wanted to clarify that the e-ink display would use a different driver to what this library implements.

As for your SPI question: the only reason why this is slow for OLED-js specifically is due to how the [standard firmata protocol](https://github.com/firmata/arduino) runs on low power / low cycle devices such as the Arduino. This library is designed to remotely control the Arduino which is running standard firmata on it. Standard firmata doesn't support SPI out of the box due to flash memory constraints (it's already a huge library). This essentially means that for me to support SPI, I manually bit bang out the SPI protocol, with several bytes for each pin flip over the USB connection from the host computer to the Arduino itself. It then streams the display buffer from there as it interprets the op codes from the standard firmata protocol. Bit banging several op codes per bit at a time is very inefficient.

I imagine that you're probably using a Raspberry Pi or similar to achieve your project? I also assume you won't have the weird bit banging over the wire limitation I have, as a result of using a more powerful device / not an Arduino with firmata. If so, then this SPI speed issue will absolutely not be a problem, and in fact SPI is designed and known for its high speed, especially compared to I2C.

Does this answer help at all? Sorry it's so long winded but I wasn't sure how much detail to include. 

Thanks for the question, and likewise nice to meet a Melburnian on Github! We probably have crossed paths at some point in our career like a meetup as you mentioned.

**Comment by pjebs** [comment]
Thanks @noopkat for the amazingly detailed response.

**Comment by noopkat** [comment]
you're welcome! I wish you the best with the project!
